---
- name: Install CentOs Packages
  yum: 
    pkg: " {{ item }}"
    state: present
  with_items: "{{ rpm_yum_packages }}"
  when: ansible_os_family == "RedHat"

- name: Install Ubuntu Packages
  apt:
    pkg: " {{ item }}"
    state: present
    force: yes
  with_items: "{{ ubuntu_apt_packages }}"
  when: ansible_os_family == "Debian"
